apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: tservices/jenkins:1.0.1  # Replace with your Jenkins image version if needed
          ports:
            - containerPort: 8080         # Jenkins web UI port
            - containerPort: 50000        # Jenkins agent port
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort  # Exposes the service on the node's IP
  selector:
    app: jenkins
  ports:
    - name: http  # Name for Jenkins web UI port
      protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port where Jenkins is running
      nodePort: 32000  # Custom NodePort (32000–32767)
    - name: agent  # Name for Jenkins agent port
      protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 32001
